from __future__ import annotations

import datetime as _dt
import re
from dataclasses import dataclass, field


def slugify(value: str) -> str:
    """Convert a project name into a valid Python package slug."""
    value = value.strip().lower()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    value = re.sub(r"_+", "-", value).strip("-")
    return value or "my_project"


@dataclass
class ProjectConfig:
    project_name: str
    project_type: str
    framework: str
    python_version: str = "3.11"
    author: str = "Your Name"
    email: str = "your.email@example.com"
    description: str = ""
    license: str = "MIT"
    use_docker: bool = True
    use_github_actions: bool = True
    include_rag: bool = False
    include_agents: bool = False
    project_slug: str = field(init=False)
    year: int = field(init=False)

    def __post_init__(self) -> None:
        self.project_slug = slugify(self.project_name)
        self.year = _dt.datetime.now().year
        if not self.description:
            self.description = f"{self.project_name} generated by Stillk."

    def to_context(self) -> dict:
        return {
            "project_name": self.project_name,
            "project_slug": self.project_slug,
            "project_type": self.project_type,
            "framework": self.framework,
            "python_version": self.python_version,
            "author": self.author,
            "email": self.email,
            "description": self.description,
            "license": self.license,
            "use_docker": self.use_docker,
            "use_github_actions": self.use_github_actions,
            "include_rag": self.include_rag,
            "include_agents": self.include_agents,
            "year": self.year,
            "stillk_version_marker": "stillk",
        }
